# Generated by Django 3.1.4 on 2020-12-17 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_novel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('novel', 'user')},
        ),
    ]
